import type { UserRole } from "@/types";

export const PERMISSIONS = {
  FARMERS_CREATE: "farmers:create",
  FARMERS_READ: "farmers:read",
  FARMERS_UPDATE: "farmers:update",
  PROCUREMENT_CREATE: "procurement:create",
  PROCUREMENT_APPROVE: "procurement:approve",
  PAYMENTS_INITIATE: "payments:initiate",
  PAYMENTS_APPROVE: "payments:approve",
  MARKETPLACE_BID: "marketplace:bid",
  MARKETPLACE_LIST: "marketplace:list",
  HUB_MANAGE: "hub:manage",
  ANALYTICS_READ: "analytics:read",
  FINANCE_SCORE: "finance:score",
  FINANCE_APPROVE: "finance:approve",
  ADMIN_ALL: "admin:all",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.FARMERS_CREATE, PERMISSIONS.FARMERS_READ, PERMISSIONS.FARMERS_UPDATE,
    PERMISSIONS.PROCUREMENT_CREATE, PERMISSIONS.PROCUREMENT_APPROVE,
    PERMISSIONS.PAYMENTS_INITIATE, PERMISSIONS.PAYMENTS_APPROVE,
    PERMISSIONS.MARKETPLACE_BID, PERMISSIONS.MARKETPLACE_LIST,
    PERMISSIONS.HUB_MANAGE, PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.FINANCE_SCORE, PERMISSIONS.FINANCE_APPROVE,
  ],
  AGENT: [PERMISSIONS.FARMERS_CREATE, PERMISSIONS.FARMERS_READ, PERMISSIONS.FARMERS_UPDATE, PERMISSIONS.PROCUREMENT_CREATE, PERMISSIONS.PAYMENTS_INITIATE],
  FARMER: [PERMISSIONS.FARMERS_READ],
  BUYER: [PERMISSIONS.MARKETPLACE_BID, PERMISSIONS.MARKETPLACE_LIST],
  HUB_MANAGER: [PERMISSIONS.HUB_MANAGE, PERMISSIONS.ANALYTICS_READ],
  ANALYST: [PERMISSIONS.FARMERS_READ, PERMISSIONS.MARKETPLACE_LIST, PERMISSIONS.ANALYTICS_READ, PERMISSIONS.FINANCE_SCORE],
};

export function getPermissionsForRole(role: UserRole): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}
